name Run Test
on:
  workflow_dispatch: {}
jobs:
  test:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Run Test
        usess: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: .
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          unityVersion: 2021.1.28f1

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results
          path: artifacts

